name: Cloudflare Access Group Updater

on:
  schedule:
    - cron: '15 */12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: PROD
    steps:

      - name: Checkout repo content
        uses: actions/checkout@v4 # Checkout the repository content

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' # Install the required Python version

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute Python script
        env:
          CF_ACCESSGROUP_ID: ${{ secrets.CF_ACCESSGROUP_ID }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_TOKEN: ${{ secrets.CF_TOKEN }}

        run: python script.py
